defaults:
  - model: standard
  - train: default
  - scm: linear
  - hydra: default
  - wandb: default
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled


model:
  n_positions: 201

scm:
  noise_types: ['gaussian', 'laplace', 'exponential', 'log-normal', 'uniform']
  x_dim: 10
  y_dim: 1
  t_dim: 1


curriculum:
    dims:
        start: 5
        inc: 1
        interval: 1000
    points:
        start: 50
        inc: 5
        interval: 10

save_every_steps: 50
keep_every_steps: 50

seed: 1234
out_dir: output/runs/

test_run: False
