defaults:
  - model: medium
  - trainer: default
  - train_data: linear
  - val_data: linear
  - hydra: default
  - wandb: default
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

train_data:
  scm:
    noise_types:
      - _target_: torch.distributions.Uniform
        _args_: [-2., 2.]
    x_dim: 10
    y_dim: 1
    t_dim: 1
    conf_factor: null

  normalize: false

model:
  n_positions: 201
  n_dims: ${eval:'${train_data.scm.x_dim} + ${train_data.scm.y_dim} + ${train_data.scm.t_dim}'}

trainer:
  learning_rate: 0.0001
  batch_size: 64
  train_steps: 50001


save_every_steps: 1000
keep_every_steps: 10000

partial_id: false

seed: 1234
out_dir: output/runs/

test_run: False
